import React, { useState, useRef } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Alert,
  ScrollView,
  TextInput,
} from "react-native";
import { Audio } from "expo-av";
import * as Print from "expo-print";
import { Ionicons } from "@expo/vector-icons";
import api from "../utils/api";
import ModernHeader from "../components/ModernHeader";
import {
  COLORS,
  SHADOWS,
  SPACING,
  BORDER_RADIUS,
  FONT_SIZES,
} from "../constants/colors";

export default function SarkariTab() {
  const [recording, setRecording] = useState(null);
  const [complaintText, setComplaintText] = useState("");
  const [loading, setLoading] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [manualInput, setManualInput] = useState("");
  const recordingTimerRef = useRef(null);

  const startRecording = async () => {
    try {
      await Audio.requestPermissionsAsync();
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      });
      const { recording } = await Audio.Recording.createAsync(
        Audio.RecordingOptionsPresets.HIGH_QUALITY
      );
      setRecording(recording);
      setRecordingTime(0);

      recordingTimerRef.current = setInterval(() => {
        setRecordingTime((t) => t + 1);
      }, 1000);
    } catch (_error) {
      Alert.alert("Error", "Could not start recording.");
    }
  };

  const stopRecording = async () => {
    setLoading(true);
    if (recordingTimerRef.current) {
      clearInterval(recordingTimerRef.current);
    }

    try {
      await recording.stopAndUnloadAsync();
      const uri = recording.getURI();
      const formData = new FormData();
      formData.append("file", {
        uri,
        name: "complaint.m4a",
        type: "audio/m4a",
      });
      const res = await api.post("/api/sarkari/draft", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      setComplaintText(res.data.letter || res.data);
    } catch (_error) {
      Alert.alert("Error", "Failed to process audio.");
    } finally {
      setLoading(false);
      setRecording(null);
      setRecordingTime(0);
    }
  };

  const processManualInput = async () => {
    if (!manualInput.trim()) {
      Alert.alert("Empty Input", "Please type a complaint or description.");
      return;
    }

    setLoading(true);
    try {
      // Send manual text to backend for processing if available
      const res = await api.post("/api/sarkari/draft-text", {
        complaint: manualInput,
      });
      setComplaintText(res.data.letter || res.data);
      setManualInput("");
    } catch (_error) {
      // If API doesn't support text, just use it as-is
      setComplaintText(manualInput);
      setManualInput("");
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = async () => {
    if (!complaintText) return;

    try {
      await Print.printAsync({
        html: `
          <html>
            <head>
              <style>
                body { font-family: Arial; padding: 20px; line-height: 1.6; }
                h1 { color: #333; margin-bottom: 20px; }
                p { color: #666; margin: 10px 0; }
              </style>
            </head>
            <body>
              <h1>Official Complaint Letter</h1>
              <p style="white-space: pre-wrap;">${complaintText}</p>
              <p style="margin-top: 30px; color: #999; font-size: 12px;">
                Generated by SahiHai - Your Digital Rights Assistant
              </p>
            </body>
          </html>
        `,
      });
      Alert.alert("Success", "PDF generated successfully!");
    } catch (_error) {
      Alert.alert("Error", "Failed to generate PDF.");
    }
  };

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs < 10 ? "0" : ""}${secs}`;
  };

  return (
    <View style={styles.wrapper}>
      <ModernHeader
        title="Sarkari Saathi"
        subtitle="Generate official complaint letters"
      />
      <ScrollView style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Sarkari Saathi</Text>
          <Text style={styles.headerSubtitle}>
            Generate official complaint letters easily
          </Text>
        </View>

        {/* Voice Recording Section */}
        {!complaintText && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Record Your Complaint</Text>

            <View style={[styles.recordingCard, SHADOWS.md]}>
              <View style={styles.recordingContent}>
                <Ionicons
                  name={recording ? "mic" : "mic-outline"}
                  size={48}
                  color={recording ? COLORS.DANGER : COLORS.ACCENT}
                />

                {recording && (
                  <View style={styles.timerContainer}>
                    <Text style={styles.timerText}>
                      {formatTime(recordingTime)}
                    </Text>
                    <View style={styles.recordingIndicator}>
                      <View style={styles.recordingDot} />
                      <Text style={styles.recordingText}>Recording...</Text>
                    </View>
                  </View>
                )}

                {!recording && (
                  <Text style={styles.recordingPrompt}>
                    Tap to record your complaint details
                  </Text>
                )}
              </View>

              <TouchableOpacity
                style={[
                  styles.recordButton,
                  recording && styles.recordButtonActive,
                  loading && styles.recordButtonDisabled,
                ]}
                onPress={recording ? stopRecording : startRecording}
                disabled={loading}
              >
                {loading ? (
                  <ActivityIndicator color={COLORS.WHITE} />
                ) : (
                  <Ionicons
                    name={recording ? "stop" : "mic"}
                    size={28}
                    color={COLORS.WHITE}
                  />
                )}
              </TouchableOpacity>
            </View>

            {/* Manual Input Section */}
            <View style={[styles.manualCard, SHADOWS.md]}>
              <Text style={styles.manualTitle}>Or Type Your Complaint</Text>
              <TextInput
                style={styles.textInput}
                placeholder="Describe your complaint in detail..."
                placeholderTextColor={COLORS.TEXT_LIGHT}
                multiline
                numberOfLines={6}
                value={manualInput}
                onChangeText={setManualInput}
                editable={!loading}
              />
              <TouchableOpacity
                style={[
                  styles.processButton,
                  loading && styles.processButtonDisabled,
                ]}
                onPress={processManualInput}
                disabled={loading}
              >
                {loading ? (
                  <ActivityIndicator color={COLORS.WHITE} />
                ) : (
                  <>
                    <Ionicons
                      name="document-text"
                      size={18}
                      color={COLORS.WHITE}
                    />
                    <Text style={styles.processButtonText}>
                      Generate Letter
                    </Text>
                  </>
                )}
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* Generated Letter Section */}
        {complaintText && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Drafted Letter</Text>

            <View style={[styles.letterCard, SHADOWS.md]}>
              <View style={styles.letterHeader}>
                <Ionicons
                  name="document-text"
                  size={24}
                  color={COLORS.ACCENT}
                />
                <Text style={styles.letterHeaderText}>
                  Official Complaint Letter
                </Text>
              </View>

              <ScrollView
                style={styles.letterContent}
                scrollEnabled
                nestedScrollEnabled
              >
                <Text style={styles.letterText}>{complaintText}</Text>
              </ScrollView>
            </View>

            {/* Action Buttons */}
            <View style={styles.actionButtons}>
              <TouchableOpacity
                style={[styles.pdfButton, SHADOWS.sm]}
                onPress={generatePDF}
              >
                <Ionicons name="download" size={18} color={COLORS.WHITE} />
                <Text style={styles.pdfButtonText}>Download PDF</Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.editButton, SHADOWS.sm]}
                onPress={() => {
                  setComplaintText("");
                  setRecordingTime(0);
                }}
              >
                <Ionicons name="create" size={18} color={COLORS.ACCENT} />
                <Text style={styles.editButtonText}>New Letter</Text>
              </TouchableOpacity>
            </View>

            {/* Tips Section */}
            <View style={styles.tipsSection}>
              <View style={styles.tipItem}>
                <Ionicons
                  name="information-circle"
                  size={20}
                  color={COLORS.INFO}
                />
                <Text style={styles.tipText}>
                  Save the PDF and submit it to the relevant government
                  department.
                </Text>
              </View>
              <View style={styles.tipItem}>
                <Ionicons
                  name="information-circle"
                  size={20}
                  color={COLORS.INFO}
                />
                <Text style={styles.tipText}>
                  Keep a copy for your records and follow-up inquiries.
                </Text>
              </View>
            </View>
          </View>
        )}

        {/* Empty State */}
        {!complaintText && (
          <View style={styles.emptyContainer}>
            <Ionicons name="document-outline" size={64} color={COLORS.ACCENT} />
            <Text style={styles.emptyText}>No Letter Generated</Text>
            <Text style={styles.emptySubText}>
              Start by recording or typing your complaint
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: COLORS.BG_SECONDARY,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.BG_SECONDARY,
  },
  header: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  headerTitle: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: "700",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.sm,
  },
  headerSubtitle: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.TEXT_SECONDARY,
  },
  section: {
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "600",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.md,
  },
  recordingCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.lg,
  },
  recordingContent: {
    alignItems: "center",
    marginBottom: SPACING.lg,
  },
  timerContainer: {
    marginTop: SPACING.lg,
    alignItems: "center",
  },
  timerText: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: "700",
    color: COLORS.DANGER,
    marginBottom: SPACING.sm,
  },
  recordingIndicator: {
    flexDirection: "row",
    alignItems: "center",
  },
  recordingDot: {
    width: 12,
    height: 12,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.DANGER,
    marginRight: SPACING.sm,
    animation: "pulse",
  },
  recordingText: {
    color: COLORS.DANGER,
    fontWeight: "600",
    fontSize: FONT_SIZES.md,
  },
  recordingPrompt: {
    marginTop: SPACING.md,
    fontSize: FONT_SIZES.md,
    color: COLORS.TEXT_SECONDARY,
    textAlign: "center",
  },
  recordButton: {
    width: 70,
    height: 70,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.ACCENT,
    justifyContent: "center",
    alignItems: "center",
  },
  recordButtonActive: {
    backgroundColor: COLORS.DANGER,
  },
  recordButtonDisabled: {
    opacity: 0.6,
  },
  manualCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
  },
  manualTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "600",
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.md,
  },
  textInput: {
    borderWidth: 1,
    borderColor: COLORS.GRAY_MEDIUM,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    fontSize: FONT_SIZES.md,
    color: COLORS.TEXT_PRIMARY,
    textAlignVertical: "top",
    marginBottom: SPACING.md,
    minHeight: 120,
  },
  processButton: {
    backgroundColor: COLORS.SUCCESS,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
  },
  processButtonDisabled: {
    opacity: 0.6,
  },
  processButtonText: {
    color: COLORS.WHITE,
    fontWeight: "600",
    fontSize: FONT_SIZES.md,
    marginLeft: SPACING.md,
  },
  letterCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  letterHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.lg,
    paddingBottom: SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.GRAY_MEDIUM,
  },
  letterHeaderText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "600",
    color: COLORS.TEXT_PRIMARY,
    marginLeft: SPACING.md,
  },
  letterContent: {
    maxHeight: 300,
    marginBottom: SPACING.lg,
  },
  letterText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 22,
  },
  actionButtons: {
    flexDirection: "row",
    gap: SPACING.md,
    marginBottom: SPACING.lg,
  },
  pdfButton: {
    flex: 1,
    backgroundColor: COLORS.DANGER,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
  },
  pdfButtonText: {
    color: COLORS.WHITE,
    fontWeight: "600",
    fontSize: FONT_SIZES.md,
    marginLeft: SPACING.md,
  },
  editButton: {
    flex: 1,
    backgroundColor: `${COLORS.ACCENT}20`,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.ACCENT,
  },
  editButtonText: {
    color: COLORS.ACCENT,
    fontWeight: "600",
    fontSize: FONT_SIZES.md,
    marginLeft: SPACING.md,
  },
  tipsSection: {
    marginBottom: SPACING.xxl,
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: SPACING.md,
    backgroundColor: COLORS.WHITE,
    padding: SPACING.lg,
    borderRadius: BORDER_RADIUS.md,
  },
  tipText: {
    flex: 1,
    fontSize: FONT_SIZES.sm,
    color: COLORS.TEXT_SECONDARY,
    marginLeft: SPACING.md,
    lineHeight: 20,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "600",
    color: COLORS.TEXT_PRIMARY,
    marginTop: SPACING.lg,
  },
  emptySubText: {
    fontSize: FONT_SIZES.sm,
    color: COLORS.TEXT_SECONDARY,
    marginTop: SPACING.sm,
    textAlign: "center",
    paddingHorizontal: SPACING.lg,
  },
});
