
import { User } from '../../../domain/User';
import { ChatSession } from '../../../domain/ChatSession';
import { IChatSessionRepository } from '../repositories/IChatSessionRepository';
import { v4 as uuidv4 } from 'uuid';

export class InitiateChat {
  constructor(private readonly chatSessionRepository: IChatSessionRepository) {}

  async execute(user: User): Promise<ChatSession> {
    const newChatSession: ChatSession = {
      id: '', // Will be generated by the database
      user,
      threadId: uuidv4(), // Generate a unique threadId
      activeModel: user.preferredLLMProvider || 'Gemini-Flash',
      messageHistory: [],
      createdAt: new Date(),
    };
    return this.chatSessionRepository.create(newChatSession);
  }
}
