import PDFDocument from "pdfkit";
import { Response } from "express";

interface LetterData {
  letterContent: string;
  transcript?: string;
  generatedDate?: Date;
  userInfo?: {
    name?: string;
    address?: string;
    phone?: string;
  };
}

export function generateComplaintLetterPDF(
  res: Response,
  data: LetterData
): void {
  const doc = new PDFDocument({
    size: "A4",
    margins: {
      top: 50,
      bottom: 50,
      left: 50,
      right: 50,
    },
  });

  // Set response headers for PDF download
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=complaint-letter-${Date.now()}.pdf`
  );

  // Pipe the PDF to the response
  doc.pipe(res);

  // Header
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("Official Complaint Letter", { align: "center" })
    .moveDown(0.5);

  // Date
  const dateStr = data.generatedDate
    ? data.generatedDate.toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : new Date().toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(`Date: ${dateStr}`, { align: "right" })
    .moveDown(1.5);

  // User Information (if provided)
  if (data.userInfo) {
    doc.fontSize(11).font("Helvetica");

    if (data.userInfo.name) {
      doc.text(`From: ${data.userInfo.name}`);
    }
    if (data.userInfo.address) {
      doc.text(`Address: ${data.userInfo.address}`);
    }
    if (data.userInfo.phone) {
      doc.text(`Phone: ${data.userInfo.phone}`);
    }

    doc.moveDown(1.5);
  }

  // Horizontal line separator
  doc
    .strokeColor("#666666")
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(550, doc.y)
    .stroke()
    .moveDown(1);

  // Letter Content
  doc
    .fontSize(11)
    .font("Helvetica")
    .fillColor("#333333")
    .text(data.letterContent, {
      align: "justify",
      lineGap: 5,
    })
    .moveDown(2);

  // Signature Space
  doc
    .moveDown(2)
    .text("Yours faithfully,")
    .moveDown(2)
    .text("_______________________")
    .text("Signature")
    .moveDown(2);

  // Footer
  doc
    .fontSize(8)
    .fillColor("#999999")
    .text(
      "Generated by SahiHai - Your Digital Consumer Rights Assistant",
      50,
      doc.page.height - 50,
      {
        align: "center",
        width: doc.page.width - 100,
      }
    )
    .text(`Generated on: ${new Date().toISOString()}`, {
      align: "center",
    });

  // Finalize the PDF
  doc.end();
}

export function generateSimplePDF(res: Response, letterContent: string): void {
  generateComplaintLetterPDF(res, {
    letterContent,
    generatedDate: new Date(),
  });
}

export function generateComplaintLetterPDFasBase64(
  data: LetterData
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50,
      },
    });

    const buffers: any[] = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData.toString('base64'));
    });
    doc.on('error', reject);

    // Header
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("Official Complaint Letter", { align: "center" })
      .moveDown(0.5);

    // Date
    const dateStr = data.generatedDate
      ? data.generatedDate.toLocaleDateString("en-IN", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })
      : new Date().toLocaleDateString("en-IN", {
          year: "numeric",
          month: "long",
          day: "numeric",
        });

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Date: ${dateStr}`, { align: "right" })
      .moveDown(1.5);

    // User Information (if provided)
    if (data.userInfo) {
      doc.fontSize(11).font("Helvetica");

      if (data.userInfo.name) {
        doc.text(`From: ${data.userInfo.name}`);
      }
      if (data.userInfo.address) {
        doc.text(`Address: ${data.userInfo.address}`);
      }
      if (data.userInfo.phone) {
        doc.text(`Phone: ${data.userInfo.phone}`);
      }

      doc.moveDown(1.5);
    }

    // Horizontal line separator
    doc
      .strokeColor("#666666")
      .lineWidth(1)
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke()
      .moveDown(1);

    // Letter Content
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#333333")
      .text(data.letterContent, {
        align: "justify",
        lineGap: 5,
      })
      .moveDown(2);

    // Signature Space
    doc
      .moveDown(2)
      .text("Yours faithfully,")
      .moveDown(2)
      .text("_______________________")
      .text("Signature")
      .moveDown(2);

    // Footer
    doc
      .fontSize(8)
      .fillColor("#999999")
      .text(
        "Generated by SahiHai - Your Digital Consumer Rights Assistant",
        50,
        doc.page.height - 50,
        {
          align: "center",
          width: doc.page.width - 100,
        }
      )
      .text(`Generated on: ${new Date().toISOString()}`, {
        align: "center",
      });

    // Finalize the PDF
    doc.end();
  });
}
